task:
  name: Deploy
  env:
    CIRRUS_WORKING_DIR: "/tmp/ci"
    SECRET_TOKEN: ENCRYPTED[93e65cbc28b74718217f312af0141d6711069a6ad87b9add8025826bcfd633cf48ef8ec6425232c4c7aa31f4b7ce126d]
    DEBIAN_FRONTEND: noninteractive
    LANGUAGE: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  container:
    dockerfile: Dockerfile
    cpu: 4
    memory: 4G
    ports:
              - 8080
              - 5432
    additional_containers:
      - name: postgres
        image: postgres
        ports:
              - 8080
              - 5432
        
  start_script:
    - bash start.sh
